baseURL = "https://vittoriomattei.com"
relativeurls=true
languageCode = "en-us"
title = "Vittorio Mattei"
theme = "FixIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Rèsumè"
    url = "/resume/resume.pdf"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[params]
  description = "Vittorio Mattei's personal website and blog. Software engineer talking about programming, design, python and the IT world." # site description
  keywords = "portfolio resume blog coding programming python software engineering developer" # site keywords

  license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
[params.home]
  paginate = 0
  [params.home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/images/me/avatar.jpeg"
    avatarMenu = ""
    title = "Vittorio Mattei"
    subtitle = "A coding space"       # Subtitle
    typeit = true
    social = true
    disclaimer = ""
  [params.home.posts]
    enable = false
    paginate = 0


[params.social]
    GitHub = "vittoriom94"
    Linkedin = "vittorio-mattei"
    Email   = "vimattei94@gmail.com"

[params.share]
Twitter = true
Facebook = true
Reddit = true
Linkedin = true

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Vittorio Mattei"

  [params.publisher]
    name = "Vittorio Mattei"