name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      resume: ${{ steps.filter.outputs.resume }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            resume:
              - 'content/resume/**'
  compile_resume:
    needs: changes
    if: ${{ needs.changes.outputs.resume == 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX resume
        uses: xu-cheng/latex-action@v2
        with:
            root_file: resume.tex
            working_directory: content/resume
            latexmk_use_xelatex: true
      - name: Move PDF
        run: mv content/resume/resume.pdf static/resume/resume.pdf
      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Upload PDF by Github Actions
            file_pattern: 'static/resume/*.pdf'
  deploy:
    if: ${{ always() }}
    needs: compile_resume
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --gc --minify
        env:
          HUGO_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
